model:
  name: EMGCombinedModel # EMGLSTMModel, EMGCombinedModel
  input_size: 1
  hidden_size: 64
  num_layers: 1
  dropout: 0.5

data:
  root_dir: data
  emg_dir: EMG
  metadata_dir: metadata.csv

train:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  criterion: mse
  optimizer: adam

output:
  path: ckpt
  