model:
  name: EMGCombinedBiLSTMModel # EMGLSTMModel, EMGCombinedModel, EMGCombinedBiLSTMModel
  input_size: 1
  hidden_size: 128
  num_layers: 3
  dropout: 0.2

data:
  root_dir: data
  emg_dir: EMG
  metadata_dir: metadata.csv

train:
  epochs: 1000
  batch_size: 2
  learning_rate: 0.001
  criterion: mae
  optimizer: adam

output:
  path: ckpt
  